<?php

namespace Modules\Product\Database\CustomSeeders;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use LaravelIdea\Helper\Modules\Attributes\Entities\_IH_Category_QB;
use Modules\Attributes\Entities\Category;

class FurnitureProductSeeder
{
    public static function getProducts(): array
    {
        return [
            [
                'name' => 'Modern Living Dining Room  with Solid Wood',
                'slug' => 'modern-living-dining-room-with-solid-wood',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Fine Fabric Side Chairs-The utility fabric side chairs have the advantages of good permeability and comfortability. Upholstered seat and chair back filled with sponge are soft and full of elasticity.In a classic shape with an open back, so you feel free and airy even if you\'re chained to any desk or table.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Modern design accent armchair, elegantly curved silhouette provides maximum comfort, is perfect for decor your living room bedroom dining room office.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Frame constructions have been rigorously tested to simulate the home and transportation environments for improved durability.Solid wood legs come in a natural finish. Corners are glued, blocked and stapled. High-quality plush high-density foam cushioning is upholstered.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">EASY TO ASSEMBLE-The package of the chairs comes with a detailed instruction manual and all the accessories.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">If you have any questions, please feel free to contact us via email and we will give you a satisfactory solution immediately</span></li></ul>',
                'image_id' => '513',
                'price' => '500',
                'sale_price' => '473',
                'cost' => '413',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-27 18:06:06',
                'updated_at' => '2023-01-03 18:22:05',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Hall Room Chair',
                'slug' => 'hall-room-chair',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Fine Fabric Side Chairs-The utility fabric side chairs have the advantages of good permeability and comfortability. Upholstered seat and chair back filled with sponge are soft and full of elasticity.In a classic shape with an open back, so you feel free and airy even if you\'re chained to any desk or table.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Modern design accent armchair, elegantly curved silhouette provides maximum comfort, is perfect for decor your living room bedroom dining room office.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Frame constructions have been rigorously tested to simulate the home and transportation environments for improved durability.Solid wood legs come in a natural finish. Corners are glued, blocked and stapled. High-quality plush high-density foam cushioning is upholstered.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">EASY TO ASSEMBLE-The package of the chairs comes with a detailed instruction manual and all the accessories.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">If you have any questions, please feel free to contact us via email and we will give you a satisfactory solution immediately.</span></li></ul>',
                'image_id' => '488',
                'price' => '250',
                'sale_price' => '225',
                'cost' => '200',
                'badge_id' => '2',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-27 18:24:40',
                'updated_at' => '2023-01-03 18:21:59',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'stylish Hall Room Chair',
                'slug' => 'hall-room-chair-1',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Fine Fabric Side Chairs-The utility fabric side chairs have the advantages of good permeability and comfortability. Upholstered seat and chair back filled with sponge are soft and full of elasticity.In a classic shape with an open back, so you feel free and airy even if you\'re chained to any desk or table.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Modern design accent armchair, elegantly curved silhouette provides maximum comfort, is perfect for decor your living room bedroom dining room office.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Frame constructions have been rigorously tested to simulate the home and transportation environments for improved durability.Solid wood legs come in a natural finish. Corners are glued, blocked and stapled. High-quality plush high-density foam cushioning is upholstered.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">EASY TO ASSEMBLE-The package of the chairs comes with a detailed instruction manual and all the accessories.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">If you have any questions, please feel free to contact us via email and we will give you a satisfactory solution immediately.</span></li></ul>',
                'image_id' => '489',
                'price' => '250',
                'sale_price' => '225',
                'cost' => '200',
                'badge_id' => '2',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-27 18:50:54',
                'updated_at' => '2023-01-03 18:21:52',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Solid Wood table',
                'slug' => 'solid-wood-table',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Fine Fabric Side Chairs-The utility fabric side chairs have the advantages of good permeability and comfortability. Upholstered seat and chair back filled with sponge are soft and full of elasticity.In a classic shape with an open back, so you feel free and airy even if you\'re chained to any desk or table.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Modern design accent armchair, elegantly curved silhouette provides maximum comfort, is perfect for decor your living room bedroom dining room office.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Frame constructions have been rigorously tested to simulate the home and transportation environments for improved durability.Solid wood legs come in a natural finish. Corners are glued, blocked and stapled. High-quality plush high-density foam cushioning is upholstered.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">EASY TO ASSEMBLE-The package of the chairs comes with a detailed instruction manual and all the accessories.</span></li></ul>',
                'image_id' => '490',
                'price' => '500',
                'sale_price' => '450',
                'cost' => '400',
                'badge_id' => '2',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 10:53:48',
                'updated_at' => '2023-01-03 18:21:45',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Doug Wooden Table',
                'slug' => 'solid-wood-table-1',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Fine Fabric Side Chairs-The utility fabric side chairs have the advantages of good permeability and comfortability. Upholstered seat and chair back filled with sponge are soft and full of elasticity.In a classic shape with an open back, so you feel free and airy even if you\'re chained to any desk or table.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Modern design accent armchair, elegantly curved silhouette provides maximum comfort, is perfect for decor your living room bedroom dining room office.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Frame constructions have been rigorously tested to simulate the home and transportation environments for improved durability.Solid wood legs come in a natural finish. Corners are glued, blocked and stapled. High-quality plush high-density foam cushioning is upholstered.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">EASY TO ASSEMBLE-The package of the chairs comes with a detailed instruction manual and all the accessories.</span></li></ul>',
                'image_id' => '490',
                'price' => '500',
                'sale_price' => '450',
                'cost' => '400',
                'badge_id' => '2',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 11:15:06',
                'updated_at' => '2023-01-03 18:21:36',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Small Dining Table',
                'slug' => 'small-dining-table',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '491',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 11:23:38',
                'updated_at' => '2023-01-03 18:21:29',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Coffee Table',
                'slug' => 'small-dining-table-1',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '492',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 11:30:23',
                'updated_at' => '2023-01-03 18:21:22',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Bombay Chair',
                'slug' => 'bombay-chair',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '494',
                'price' => '700',
                'sale_price' => '600',
                'cost' => '500',
                'badge_id' => null,
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 11:41:17',
                'updated_at' => '2023-01-03 18:21:14',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'stylish Wood Sofa',
                'slug' => 'stylish-wood-sofa',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '495',
                'price' => '600',
                'sale_price' => '525',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 11:47:19',
                'updated_at' => '2023-01-03 18:21:05',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Stylish Black Colour  Sofa',
                'slug' => 'stylish-wood-sofa-1',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '496',
                'price' => '600',
                'sale_price' => '525',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 11:47:27',
                'updated_at' => '2023-01-03 18:20:55',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Single  Sofa',
                'slug' => 'stylish-wood-sofa-2',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '499',
                'price' => '600',
                'sale_price' => '525',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 11:55:02',
                'updated_at' => '2023-01-03 18:19:54',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Modern  high height sofa',
                'slug' => 'stylish-wood-sofa-3',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '500',
                'price' => '600',
                'sale_price' => '525',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 11:56:13',
                'updated_at' => '2023-01-03 18:19:47',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'plastic chair',
                'slug' => 'stylish-wood-sofa-4',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '501',
                'price' => '600',
                'sale_price' => '525',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 11:59:16',
                'updated_at' => '2023-01-03 18:19:40',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Table Tenci',
                'slug' => 'small-dining-table-2',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '497',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 12:31:38',
                'updated_at' => '2023-01-03 18:20:46',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Bamboo Chair',
                'slug' => 'small-dining-table-4',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '502',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 12:53:46',
                'updated_at' => '2023-01-03 18:19:33',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Wikker Chair',
                'slug' => 'small-dining-table-5',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '503',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 12:56:12',
                'updated_at' => '2023-01-03 18:19:26',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Wikker Chair',
                'slug' => 'small-dining-table-6',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '504',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 13:01:00',
                'updated_at' => '2023-01-03 18:19:19',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Wikker Chair',
                'slug' => 'small-dining-table-7',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '506',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 13:02:35',
                'updated_at' => '2023-01-03 18:19:11',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Ratten Chair',
                'slug' => 'small-dining-table-8',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '508',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 13:02:37',
                'updated_at' => '2023-01-03 18:19:03',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Wood cabinet',
                'slug' => 'small-dining-table-9',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '509',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 13:02:38',
                'updated_at' => '2023-01-03 18:18:56',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Raymond Wood Bed',
                'slug' => 'small-dining-table-10',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '510',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 13:02:38',
                'updated_at' => '2023-01-03 18:18:49',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Red Wood Almirah',
                'slug' => 'small-dining-table-11',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '511',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 15:58:25',
                'updated_at' => '2023-01-03 18:18:43',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Bamboo Table',
                'slug' => 'small-dining-table-12',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '512',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 16:12:37',
                'updated_at' => '2023-01-03 18:18:36',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Obhai almirah',
                'slug' => 'small-dining-table-13',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '513',
                'price' => '800',
                'sale_price' => '750',
                'cost' => '500',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 16:25:29',
                'updated_at' => '2023-01-03 18:18:30',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'care wood stool',
                'slug' => 'small-dining-table-14',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '498',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 16:25:29',
                'updated_at' => '2023-01-03 18:20:39',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Phonex Double Bed',
                'slug' => 'small-dining-table-15',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '514',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 16:54:24',
                'updated_at' => '2023-01-03 18:18:22',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Angle  Double Bed',
                'slug' => 'small-dining-table-16',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '515',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 17:05:03',
                'updated_at' => '2023-01-03 18:18:16',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Odrex Double Bed',
                'slug' => 'small-dining-table-17',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '516',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 17:05:03',
                'updated_at' => '2023-01-03 18:18:10',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Glass Top Coffee Table',
                'slug' => 'small-dining-table-18',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '517',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 17:05:04',
                'updated_at' => '2023-01-03 18:18:04',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'stylish orion sofa',
                'slug' => 'small-dining-table-20',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '518',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2022-11-28 17:05:04',
                'updated_at' => '2023-01-15 07:58:20',
                'deleted_at' => '2023-01-15 07:58:20',
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'alert(\'XXS!\')',
                'slug' => 'scriptalertxxsscript',
                'summary' => 'alert(\'XXS!\')',
                'description' => '<p>&lt;&gt;alert(\'XXS!\')&lt;/&gt;<br></p>',
                'image_id' => '526',
                'price' => '250',
                'sale_price' => '7500',
                'cost' => '500',
                'badge_id' => '5',
                'brand_id' => null,
                'status_id' => '1',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '2',
                'created_at' => '2023-01-09 19:33:56',
                'updated_at' => '2023-01-09 20:05:26',
                'deleted_at' => '2023-01-09 20:05:26',
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Glass Top Coffee Table',
                'slug' => 'small-dining-table-19',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '517',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '2',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2023-02-01 07:26:21',
                'updated_at' => '2023-02-02 22:35:17',
                'deleted_at' => '2023-02-02 22:35:17',
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Glass Top Coffee Table',
                'slug' => 'small-dining-table-19',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '517',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '2',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2023-02-03 20:07:48',
                'updated_at' => '2023-02-03 20:08:04',
                'deleted_at' => '2023-02-03 20:08:04',
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Glass Top Coffee Table',
                'slug' => 'small-dining-table-19',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '517',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '2',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2023-02-27 00:18:09',
                'updated_at' => '2023-02-27 00:18:09',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Glass Top Coffee Table',
                'slug' => 'small-dining-table-20',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '517',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '2',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2023-02-28 18:27:08',
                'updated_at' => '2023-02-28 18:27:08',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Glass Top Coffee Table',
                'slug' => 'small-dining-table-21',
                'summary' => 'Shipping & Import Fees Deposit to Bangladesh',
                'description' => '<ul class="a-unordered-list a-vertical a-spacing-mini" style="margin-right: 0px; margin-bottom: 0px; margin-left: 18px; color: rgb(15, 17, 17); padding: 0px; font-family: "Amazon Ember", Arial, sans-serif; font-size: 14px;"><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining room</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Overall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Complete your table with ladder back chairs for full dining experience.</span></li><li style="list-style: disc; overflow-wrap: break-word; margin: 0px;"><span class="a-list-item">Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area</span></li></ul>',
                'image_id' => '517',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '2',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2023-02-28 18:27:14',
                'updated_at' => '2023-02-28 18:27:14',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Glass Top Coffee Table',
                'slug' => 'small-dining-table-22',
                'summary' => 'Shipping &amp;amp; Import Fees Deposit to Bangladesh',
                'description' => 'Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining roomOverall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".Complete your table with ladder back chairs for full dining experience.Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area',
                'image_id' => '517',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '2',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2023-04-12 10:37:25',
                'updated_at' => '2023-06-05 12:49:10',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ],
            [
                'name' => 'Glass Top Coffee Table',
                'slug' => 'small-dining-table-23',
                'summary' => 'Shipping &amp;amp; Import Fees Deposit to Bangladesh',
                'description' => 'Rich, warm and inviting are a few words that describe this square shaker-style dining table. With slightly tapered legs, the classic design combines a look that will go well with many decors and is an ideal size for a kitchen eating area or small dining roomOverall table size is a squared 29.5" x 29"H. Floor clearance of 26.3".Complete your table with ladder back chairs for full dining experience.Made with solid wood in light oak finish. Assembly required. Perfect in the kitchen that allows you to create a breakfast area',
                'image_id' => '517',
                'price' => '8000',
                'sale_price' => '7500',
                'cost' => '5000',
                'badge_id' => '3',
                'brand_id' => null,
                'status_id' => '2',
                'product_type' => '1',
                'sold_count' => null,
                'min_purchase' => '1',
                'max_purchase' => '10',
                'is_refundable' => '0',
                'is_in_house' => '1',
                'is_inventory_warn_able' => '1',
                'created_at' => '2023-07-31 18:57:10',
                'updated_at' => '2023-07-31 18:57:10',
                'deleted_at' => null,
                'is_taxable' => '0',
                'tax_class_id' => null
            ]
        ];
    }

    public static function getCategory(): Builder|Model|_IH_Category_QB|Category
    {
        return Category::with('subcategory.childcategory')->where('slug', 'home-living')->first();
    }
}